image: eclipse-temurin:21-jdk

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - build
  - test
  - docker

before_script:
  - chmod +x gradlew

build:
  stage: build
  script:
    - ./gradlew --no-daemon assemble
  artifacts:
    when: always
    paths:
      - build/libs/*.jar

test:
  stage: test
  script:
    # check включает test + checkstyle + прочие проверки
    - ./gradlew --no-daemon check
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/*.xml
    paths:
      - build/reports/tests/test/
      - build/reports/checkstyle/*.xml

docker:
  stage: docker
  image: docker:24
  services:
    - name: docker:24-dind
      command: ["--tls=false"]
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
  needs: ["build", "test"]
  only:
    - main
    - tags
